language: rust
cache: cargo
deploy:
  on:
    tags: true
  provider: cargo
  token:
    secure: uQ5LpjKgtWHQhCkVFQt2iC+ItEQlnBV4TZZR6qpJOFYIcQ5Ub94bllq52ksAviWZAQ7LZ0fIWT6XmFOMK5iArQoF/sgndeW/wan7leVEgtEFPZ76I1w2xtmk/XUHX5CtMhKFM7xd8Va4MFPc0fRPvBKzghOMU/Zxky4cby3/xAnpk/zQ78kdPaYgYpK8cHlERDVQfuwjmc8cm7kMJLZ5uFNLLgO4FfCc3cK9T+wiGRGaMOpTXbj96HBUB4xVuyLztQ9zlB/roDxbKCfywT2pX5Q5ib1vtQv5mULoX5AByruEYAHs+ke7WrDFnnaxCC1KIWLDhdBsteihv46rpnYMQFMJBx5pDnOScUQUyZe1wQ6nSMDOoGEF6TuL8BAKHlv0KIBBXLS3RcNsUTkI6u0IlSjnyMVgUwe1wy2PuT/+C3bNLQyYCvMu7jwkdJYwGBzg4fjUD52WjOxcZfbneEzOOax7HPXW5NgpS9ZxsX7QT40N/+OZ8T317vBPX1vnnWNvFnR8UDADoszIByqi7WYMdX6GoGYVTxyitbILRO2Li7X5hcEiW4OMtjVkmJtJHC+ipPOytoSVG3OC2XWmGuDfL8APHSKb67I02YmuWB+5NgwhX8u6jnlkBQhE8isInUGrsvr9bB/B9givLv1Hmf4auEBsDpsBjYo1oVJt4ZpWn18=
